set dotenv-path := "./app.env"
set dotenv-load


# Create postgres container
pg_up:
    docker compose up -d

# Remove postgres container
pg_down:
    docker compose down

# Start postgres db service
pg_start:
    docker compose start

# Stop postgres db service
pg_stop:
    docker compose stop

# Create bankdb
createdb:
    docker compose exec db createdb --username=$POSTGRES_USER --owner=$POSTGRES_USER booksdb

# Drop bankdb:
dropdb:
    docker compose exec db dropdb -U $POSTGRES_USER booksdb

# Start server
server:
    uvicorn main:app --reload